export const equipmentIconId: Record<string, string> = {
  "헬멧": "equipment-helmet",
  "관": "equipment-crown",
  "장갑": "equipment-glove",
  "팔찌": "equipment-bracelet",
  "벨트": "equipment-belt",
  "부츠": "equipment-boots",
  "목걸이": "equipment-necklace",
  "귀걸이": "equipment-earring",
  "망토": "equipment-cloak",
  "공용 갑옷": "equipment-armor",
  "한 손 검": "equipment-one-hand-sword",
  "양손 검": "equipment-two-hand-sword",
  "마법 지팡이": "equipment-magic-staff",
  "이블": "equipment-evil",
  "메이스": "equipment-mace",
  "날개": "equipment-wing",
  "단도": "equipment-dagger",
  "활": "equipment-bow",
  "창": "equipment-spear",
  "피리": "equipment-flute",
  "슬링": "equipment-sling",
  "마술봉": "equipment-wand",
  "채찍": "equipment-whip",
  "낫": "equipment-scythe",
  "손톱무기": "equipment-claw",
  "책": "equipment-book",
  "빗자루": "equipment-broom",
  "쌍검": "equipment-dual-sword",
  "양손 구체": "equipment-orb",
  "쌍권총": "equipment-dual-pistol",
  "연금석": "equipment-alchemy-stone",
  "격투무기": "equipment-fist",
  "사슬낫": "equipment-chain-scythe",
  "대포": "equipment-cannon"
};

export const featureIconId: Record<string, string> = {
  "비규격 옵션": "feature-instandard-option",
  "비규격 개방옵션": "feature-open-option",
  "티어별 옵션": "feature-tier-option"
};
